### ISSUE TITLE
Formatting examples

### ISSUE THREAD

**Issue by ali-ramadhan** [beta-effect/juxta.jl#1]
If you include code examples in the README with
````
```julia <code>```
````
then you also get syntax highlighting which might make them a bit more readable.

**Comment by beta-effect** [comment]
Thanks. Fixed this in [83027c](https://github.com/beta-effect/juxta.jl/commit/83027cdd216d31b9e8dbc0eb112413ef83312b49). I was using juliia-repl instead of julia at the beginning of the code blocks.
