### ISSUE TITLE
Maybe only print attributes if there are any?

### ISSUE THREAD

**Issue by ali-ramadhan** [beta-effect/juxta.jl#4]
https://github.com/beta-effect/juxta.jl/blob/7162bef8d4807e26859fa87b89364de57ff7b428/src/juxta.jl#L38

**Comment by beta-effect** [comment]
Implemented in [c82d219](https://github.com/beta-effect/juxta.jl/commit/c82d219c09bfe71406d9f9c77f00c5e4fe8b0b8f).
